### ISSUE TITLE
Initializing  hexrd.material.Material  instance with a CIF material_file 

### ISSUE THREAD

**Issue by jj-umn** [HEXRD/hexrd#271]
Should I be able to init a Material with a CIF downloaded from either http://www.crystallography.net/ or https://materialsproject.org/ ?

Is there an example CIF file that works with  hexrd.material.Material?

**Comment by joelvbernier** [comment]
Sounds like your issue was bug related (or maybe more specifically catching a specific case), but I will upload some example CIF files to the database.  As far as what you are current trying to do, do you just need an HCP alpha Ti material?  If so, I can attach one here in hdf5 format so you can continue what you are working on.

**Comment by joelvbernier** [comment]
looks like the specific issue here was addressed in #274 and closed by PR #276
