### ISSUE TITLE
scikit-learn DBSCAN memory usage being too huge

### ISSUE THREAD

**Issue by jackshigz** [HEXRD/hexrd#279]
I am running hexrd find-orientations on a 96 GB RAM tower, but the script got killed during "using euclidean DBSCAN" because it was taking too much memory resources. Below is a stack overflow link referring to this problem: 
https://stackoverflow.com/questions/16381577/scikit-learn-dbscan-memory-usage

I believe that this is due to issue with scikit-learn DBSCAN that is requiring such large amount of memory resources, and I hope the backend of DBSCAN could be changed.

**Comment by joelvbernier** [comment]
In general, if the memory in dbscan is an issue, the thresholds used for indexing are probably allowing too many orientations through.  We have played in the past with parallel implementations of dbscan, but with proper parameter choices it shouldn't be an issue for *most* cases.  Can I have a more detailed description of the indexing problem you are trying to run?

**Comment by joelvbernier** [comment]
We probably need more checks added to prevent too large a problem for this version of dbscan as well...

**Comment by jackshigz** [comment]
I am suspecting a parameter issue.
Below is the find-orientation log
![image](https://user-images.githubusercontent.com/28308772/120837166-634e9e00-c534-11eb-917e-d012320c1c88.png)

I have run the script with different threshold values ranging from 50 to 0.01, but the script still finds 145965913 orientations. Which seems to be too many.

**Comment by joelvbernier** [comment]
Yes, 100000,000 orientations are far too many for dbscan to efficiently handle (at least this implementation). there are some options for parallel DB scan, but I suspect the problem is arising more from your choice of parameters in the search.  For volumes with more than 1000 grains, a direct search on orientation space would probably produce fewer orientations to cluster by at least an order of magnitude or two.

What you can do in the seeding step is use blob_log with a fairly large threshold value so that the number of initial search is restricted to the largest grains.  For cubic crystals, only using the first 2 HKL’s for the seeding of the search space is sufficient.  What we can also do is try a direct search with a grid on orientation space (~1e6-1e7 points).  The problem is that you don’t get as dense clusters as you do with the fiber search.

**Comment by joelvbernier** [comment]
Happy to help further with this if you attach an archive with you imageseries, material, instrument, and config file, @jackshigz.
