### ISSUE TITLE
Strange bug using ProcessPoolExecutor on Mac an Linux

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#399]
Was getting a weird error when trying to run a script that used a `ProcessPoolExecutor` with `mp_context='fork'` from `'spawn'` processes.  I tracked down at least one sneaky `'spawn'` to the calculation of `pixel_angles` in `hexrd.instrument`.  The fix, at least to start, is to force context to `'fork'` where supported, and explicitly set the context in all instances of `ProcessPoolExecutor`.

**Comment by psavery** [comment]
Yeah, currently, Linux defaults to `fork` but Mac and Windows default to `spawn`.

I'm guessing this issue was on Mac? The multiprocessing docs indicate that `spawn` should be used for Mac. If that's the case, I think we should always be able to leave everything to their defaults?

```
Changed in version 3.8: On macOS, the spawn start method is now the default.
The fork start method should be considered unsafe as it can lead to crashes
of the subprocess. See **[bpo-33725](https://bugs.python.org/issue33725).**
```

https://docs.python.org/3/library/multiprocessing.html
