### ISSUE TITLE
Broken functionality in `instrument.HEDMInstrument.extract_line_positions()`

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#441]
This merge of `fitting-fixes-jvb` broke the ability to use `instrument.HEDMInstrument.extract_line_positions()` with array-like input for the plane_data arg.  It may also have broken some of the other options specified by the kwargs, mainly the case where `do_fitting=False`.

**Comment by joelvbernier** [comment]
I am attaching a test script to run `extract_line_positions` interactively that doesn't even run for a case that I thought mirrors how the GUI is using it for powder calibration.
[extract_line_positions_test.zip](https://github.com/HEXRD/hexrd/files/8682849/extract_line_positions_test.zip)

**Comment by joelvbernier** [comment]
updated test problem in the conversation on PR #440

**Comment by psavery** [comment]
Hi @joelvbernier

This is the error I get when I try to run it with `spawn` multiprocessing:
```python
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

If I change the last line in the file to this:
```python
if __name__ == '__main__':
    multiprocessing.freeze_support()
    pwdr_lines = instr.extract_line_positions(**kwargs)
```

That seems to fix the issue.

The problem is that when we are using spawn multiprocessing, the main script file gets imported by each process. If importing the script, however, means the program will run again, then it enters an infinite recursion. On Linux, it sees that this is happening and produces an error. The last time I've seen this happen on Windows, it just runs infinitely due to the infinite recursion.

So, if we are going to run any scripts that are going to use spawn multiprocessing, they need to have:
```python
if __name__ == '__main__':
    multiprocessing.freeze_support()
    ...
```

before any multiprocessing runs.
