### ISSUE TITLE
Cannot fit a single grain

### ISSUE THREAD

**Issue by gustafsonsven** [HEXRD/hexrd#677]
Hello all,

Title says it all.  If you have a single grain in a grains.out and want to fit it we run into array shape issues.  I think this is something I saw even back in the early versions as well so a longer problem that may have a ticket already created (I didn't see one).  While it may not be something we do often, we should be able to fit a single grain at need.  Thoughts?  

Thanks - Sven

**Comment by kevindlewis23** [comment]
Can likely be fixed by adding `grains_table = np.atleast_2d(grains_table)` to the `fit_grains` method in `hexrd/fitgrains.py`.  I could be wrong so I won't make this change, someone else can confirm.  In the meantime, you do that yourself before calling `fit_grains` or use np.loadtxt(filename, ndmin=2)

**Comment by kevindlewis23** [comment]
Same thing in `hexrd/grainmap/nfutil.py`, `gen_trial_exp_data` can support this by changing `ff_data=np.loadtxt(grain_out_file)` to `ff_data=np.loadtxt(grain_out_file, ndmin=2)`
